<?php
declare(strict_types=1);

return [
    [
        'full_name' => 'Steven Juma Kibabaje',
        'registration_number' => 'IRDP/ODICT/MA25/0001',
        'programme' => 'ODICT',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => 'IRDP/ODICT/MA26/0002',
    ],
    [
        'full_name' => 'Neema Asha Mfinanga',
        'registration_number' => 'IRDP/BTCRP/MA25/0002',
        'programme' => 'BTCRP',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => 'IRDP/BTCRP/MA26/0003',
    ],
    [
        'full_name' => 'Baraka Musa Mushi',
        'registration_number' => 'IRDP/BTCCD/MA25/0003',
        'programme' => 'BTCCD',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => 'IRDP/BTCCD/MA26/0004',
    ],
    [
        'full_name' => 'Rehema John Mallya',
        'registration_number' => 'IRDP/ODICT/MA25/0004',
        'programme' => 'ODICT',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'Daniel Peter Kweka',
        'registration_number' => 'IRDP/BTCRP/MA25/0005',
        'programme' => 'BTCRP',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'Amina Hassan Said',
        'registration_number' => 'IRDP/BTCCD/MA25/0006',
        'programme' => 'BTCCD',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'Joseph Paul Mrema',
        'registration_number' => 'IRDP/ODICT/MA25/0007',
        'programme' => 'ODICT',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'Fatuma Ali Mollel',
        'registration_number' => 'IRDP/BTCRP/MA25/0008',
        'programme' => 'BTCRP',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'Musa Ibrahim Kimaro',
        'registration_number' => 'IRDP/BTCCD/MA25/0009',
        'programme' => 'BTCCD',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'Grace Esther Massawe',
        'registration_number' => 'IRDP/ODICT/MA25/0010',
        'programme' => 'ODICT',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'Peter James Mgimwa',
        'registration_number' => 'IRDP/BTCRP/MA25/0011',
        'programme' => 'BTCRP',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'Halima Omar Nyerere',
        'registration_number' => 'IRDP/BTCCD/MA25/0012',
        'programme' => 'BTCCD',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'John David Mkude',
        'registration_number' => 'IRDP/ODICT/MA25/0013',
        'programme' => 'ODICT',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'Zawadi Rose Mwakalinga',
        'registration_number' => 'IRDP/BTCRP/MA25/0014',
        'programme' => 'BTCRP',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
    [
        'full_name' => 'Emmanuel Daniel Msuya',
        'registration_number' => 'IRDP/BTCCD/MA25/0015',
        'programme' => 'BTCCD',
        'academic_cycle' => '2025/2026',
        'legacy_registration' => null,
    ],
];
