<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/bootstrap.php';require_role('ADMIN');$error='';$errors=[];$result=null;
if($_SERVER['REQUEST_METHOD']==='POST'){try{verify_csrf();$mode=text_input($_POST,'mode',20);
    if($mode==='preview'){$rows=parse_import_file($_FILES['file']??[]);$_SESSION['student_import']=['admin'=>(int)current_user()['id'],'expires'=>time()+1800,'nonce'=>bin2hex(random_bytes(16)),'rows'=>preview_import($pdo,$rows)];}
    elseif($mode==='commit'){$preview=$_SESSION['student_import']??null;if(!$preview || $preview['admin']!==(int)current_user()['id'] || $preview['expires']<time() || !is_string($_POST['nonce']??null) || !hash_equals($preview['nonce'],$_POST['nonce'])){throw new RuntimeException('Preview expired. Upload the file again.');}if(($_POST['confirm']??'')!=='1'){throw new RuntimeException('Confirm importing valid rows.');}unset($_SESSION['student_import']);$result=commit_import($pdo,$preview['rows'],(int)current_user()['id']);}
    else{throw new RuntimeException('Invalid import action.');}
}catch(Throwable $e){$error=page_error($e,$errors);}}
$preview=$_SESSION['student_import']['rows']??[];$pageTitle='Bulk Student Import';require_once __DIR__.'/../includes/header.php';?>
<section class="panel"><h1>Bulk import Students</h1><p>UTF-8 CSV or XLSX, maximum 5 MB and <?=IMPORT_MAX_ROWS?> rows. Use active department and programme codes. Imported accounts require individual, identity-verified activation through <a href="<?=e(url('admin/recovery.php'))?>">Account recovery</a>.</p><p><a class="btn secondary" href="<?=e(url('admin/import_template.php?format=csv'))?>">CSV template</a> <a class="btn secondary" href="<?=e(url('admin/import_template.php?format=xlsx'))?>">XLSX template</a></p><?php if($error):?><div class="alert danger"><?=e($error)?></div><?php endif;?><form method="post" enctype="multipart/form-data"><?php csrf_field();?><input type="hidden" name="mode" value="preview"><?php form_fields(['file'=>['label'=>'Student import file','type'=>'file','accept'=>'.csv,.xlsx','required'=>true]],$errors);?><button class="btn primary" type="submit">Validate and preview</button></form></section>
<?php if($result):?><section class="panel"><h2>Import outcome</h2><p>Created: <?=$result['created']?> · Skipped: <?=$result['skipped']?> · Failed: <?=$result['failed']?></p><?php foreach($result['messages'] as $message):?><p><?=e($message)?></p><?php endforeach;?><p>Distribute activation credentials only after verifying each Student’s identity.</p></section><?php endif;?>
<?php if($preview):?><section class="panel"><h2>Preview</h2><div class="table-wrap"><table><thead><tr><th>Row</th><th>Name</th><th>Registration</th><th>Programme</th><th>Department</th><th>Cycle</th><th>Result</th></tr></thead><tbody><?php foreach($preview as $row):?><tr><td><?=$row['line']?></td><?php foreach(['full_name','registration_number','programme','department','academic_cycle'] as $key):?><td><?=e($row['data'][$key])?></td><?php endforeach;?><td class="<?=$row['errors']?'danger-text':''?>"><?=e($row['errors']?implode(' ',$row['errors']):'Valid')?></td></tr><?php endforeach;?></tbody></table></div><form method="post"><?php csrf_field();?><input type="hidden" name="mode" value="commit"><input type="hidden" name="nonce" value="<?=e($_SESSION['student_import']['nonce'])?>"><label><input type="checkbox" name="confirm" value="1" required> Import confirmed valid rows only; existing accounts will be skipped.</label><button class="btn primary" type="submit">Import valid rows</button></form></section><?php endif;?><?php require_once __DIR__.'/../includes/footer.php';?>
