<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/bootstrap.php';require_role('ADMIN');$error='';$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){try{verify_csrf();create_account($pdo,$_POST,(int)current_user()['id']);flash('success','Account created. Students can log in immediately and change their password voluntarily.');redirect('admin/users.php');}catch(Throwable $e){$error=page_error($e,$errors);}}
$roles=$pdo->query('SELECT id,name FROM roles ORDER BY id')->fetchAll();$offices=$pdo->query('SELECT id,name FROM offices WHERE active=1 ORDER BY name')->fetchAll();$departments=$pdo->query('SELECT id,name FROM departments WHERE active=1 ORDER BY name')->fetchAll();$programmes=[''=>'Select'];foreach($pdo->query('SELECT code,name FROM programmes WHERE active=1 ORDER BY code') as $r){$programmes[$r['code']]=$r['name'];}
$users=$pdo->query('SELECT u.id,u.username,u.full_name,u.active,u.email,r.name AS role_name,GROUP_CONCAT(o.name SEPARATOR ", ") AS offices FROM users u INNER JOIN roles r ON r.id=u.role_id LEFT JOIN user_offices uo ON uo.user_id=u.id LEFT JOIN offices o ON o.id=uo.office_id GROUP BY u.id ORDER BY u.id DESC')->fetchAll();
$departmentOfficeId=(int)$pdo->query('SELECT office_id FROM workflow_steps WHERE step_number=7')->fetchColumn();
$pageTitle='Manage Users';require_once __DIR__.'/../includes/header.php';?>
<div class="page-heading"><h1>Manage users</h1></div><div class="two-col"><section class="panel"><h2>Create account</h2><?php if($error):?><div class="alert danger"><?=e($error)?></div><?php endif;?><form method="post" data-department-office-id="<?= $departmentOfficeId ?>"><?php csrf_field();form_fields([
'full_name'=>['label'=>'Full name','required'=>true,'maxlength'=>160],'username'=>['label'=>'Username / registration number','required'=>true,'maxlength'=>100],
'email'=>['label'=>'Email (unverified until identity verification)','type'=>'email','maxlength'=>160],
'password'=>['label'=>'Initial password ('.PASSWORD_MIN_LENGTH.'-'.PASSWORD_MAX_LENGTH.' characters)','type'=>'password','required'=>true,'maxlength'=>PASSWORD_MAX_LENGTH,'autocomplete'=>'new-password'],
'confirm_password'=>['label'=>'Confirm initial password','type'=>'password','required'=>true,'maxlength'=>PASSWORD_MAX_LENGTH,'autocomplete'=>'new-password'],
'role_id'=>['label'=>'Role','type'=>'select','required'=>true,'options'=>option_rows($roles)],'office_id'=>['label'=>'Explicit office review authority (required for Officers)','type'=>'select','options'=>option_rows($offices)],
'department_id'=>['label'=>'Department (required for Students and departmental reviewers)','type'=>'select','options'=>option_rows($departments)],
'programme'=>['label'=>'Student programme','type'=>'select','options'=>$programmes],'academic_year'=>['label'=>'Student academic cycle','type'=>'select','options'=>[''=>'Select'] + array_column($pdo->query('SELECT label FROM academic_cycles WHERE active=1 ORDER BY label DESC')->fetchAll(),'label','label'),'value'=>date('Y').'/'.((int)date('Y')+1)]],$errors);?><button class="btn primary" type="submit">Create account</button></form></section>
<section class="panel"><h2>Accounts</h2><div class="table-wrap"><table><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Office authority</th><th>Status</th></tr></thead><tbody><?php foreach($users as $user):?><tr><td><?=e($user['full_name'])?></td><td><?=e($user['username'])?></td><td><?=e($user['role_name'])?></td><td><?=e($user['offices']??'None')?></td><td><?=$user['active']?'Active':'Inactive'?></td></tr><?php endforeach;?></tbody></table></div></section></div><?php require_once __DIR__.'/../includes/footer.php';?>
